airbnb:
  outputs:
    dev:
      type: snowflake
      account: qvfezmi-nx33373
      user: dbt

      role: TRANSFORM
      private_key: "-----BEGIN ENCRYPTED PRIVATE KEY-----
MIIFJDBWBgkqhkiG9w0BBQ0wSTAxBgkqhkiG9w0BBQwwJAQQiRmLJTxA7/AUgQRU
de7uBQICCAAwDAYIKoZIhvcNAgkFADAUBggqhkiG9w0DBwQIR6Dh+PUBKZIEggTI
ZIK6VZR+gEBvuhOSoxOO3nUzDOTwx8US2cIBzrAiwP1oRm8YePEXuErYOcoUqFjA
RWSlmtL1fv5iFFTp3UD2xwX0nMdU2LTHgNfloLe3MhIcgXSu3/PxgNvWvr8UcxLU
ckVZBeDdb4Hbc1RctJnavg4gxSoQT2s78S+jn+fKmQ63mk2uQ1bmtF7UNAp0s4Pl
WjEZ9K1iFNbm1n9PS4a1oi82WYQMKzsk7D5gY/qoQjyhMEJI3pgqBYhGO56sOJUx
uNPIHi1PxRY1WfO2FyQJJnM+Wt4y3yHsrVqqckp9+SVUdq6QU2DliIoir4Xbe41h
m9d3frVfefHikQKjtKJ8u1pN+sFOCMrXzm9ZjPPDS/E2jngHm7dX4n7aFTZn2nc+
R+Y0d2bAi+m6ClJWZY/a/o/i3cQTqBaXq3RmzY9dLmOd0M0VpNIaeA2VCnIlZE/b
LU0WvyMxVsUenJYNQobTDDh/lhsZcOLPHicyFV5+aLeMEXr8XMVOcLcCnX8OalsK
xzDiYMGBR0kOJkutog8PGIPLtGKhpEoQc/qrN5Zam41u3bByLjbP3DiKNqGrulxr
gQt52S21uobEqLW5LhEKd7mqPkrr998nUDAD0e7e9hR2iPq1coJyht/VApxbg5eR
aEHizsM5T7k/gIryDT43AOnmrwUc6zBLxr130dSRpU55eG2G1vUkVcARJg2w/cU/
KWBVHLwdQifG+31WEXB2NLXrT+dpgNNQkZv389JAxFZlFs1e/2tDSpNJqo2jppvb
8DyaKTOcQkRifHCcQdnc5TWOhkS0zLWN2mwhQyNbdNDl4VegeR9zCX4RTmtUZQRj
O8NIt94oxyRWz29hhrvhx/O1JBlmKdOaBrEP/TmXUPff8mkegYhPxq9zhNdXz0Sg
nXp9jGhSiQIMcQcqayvq3SAXVjyRKjvBesXSsC7X0Xfmp0UIBqyNxbyGmrQRznUo
1muiQSjFb0wee206//Hv3H/H42CbaTY0JPbm8Pnhn7t9jNGZlw3EC1wEjhr7CCS1
NFISVYgLAMILoYIyKp4sM4rxm2ytSrxCWGRdZ/N1wk7t3uGMTVBEtHKZdNVQUWpY
1ei3rVfeSUjDptPuFPcyNEopEm0eRfI84yjMT9vLET4T0Pbj/84iIWnQOjOh7mj7
5ivu3H0+GOqPsXsHHhCLMyw4f1YQfCUe9cravfvCQHzC+ladMbMOJR/h3HtNB4/H
EbZwxS9RscU3SLcYn6YKSwZRzY+4kpv4Jxcz41NZgvt2yiZU3vQzsn7zqGY56OXJ
Ice9W+l2P3/+zfUdJ8QVMNVVlJbivG3gvsZIgQk/Nvyafl4hl2kx6cfi4GdOSbAy
bYKAMMD96hR3B+CDixaJrV7WVEi4pdYQgkX8bk/ZY+7xLvcUkBmIFZYkeLgFkQ+T
/AhuSWcIP5pJFnnfX6yXAebX8BYnQNIJbe1QDET1ucLwEsr/k8QMfQS8AGRqmMx+
T96oHOuCnSxzTz4HfazP9vwZjqd3EwhzO5yoPtvWBg8EyVNMRbcSPjITIea9v1wU
lelN0SZNxbM4vox9jGQ1wkoEpXdDIHw2cIR8hQmM0+1qEt2LsYQ271zkV2QKFQWr
2IkGW4euP/V8B2gVTYNMZ5cgzDn9stOc
-----END ENCRYPTED PRIVATE KEY-----"
      private_key_passphrase: Arun

      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
  target: dev